Aggiunto pulsante "Social comunitari"
MozillaItalia/mozitahub_bot pull request #39
Opened 2020-04-03 08:47 UTC by ilyasmg

#37

2020-04-05 13:29 UTC, Sav22999 commented
@ilyasmg fai anche gli altri issue? Nel caso non approvo subito questa PR.
Inoltre, devi incrementare in numero di versione

2020-04-05 20:55 UTC, ilyasmg commented
Aggiunto #40 e #35

2020-04-05 21:06 UTC, Sav22999 requested changes

2020-04-05 21:06 UTC, Sav22999 commented on frasi.json
> +    "help": "Questa è la lista di comandi a tua disposizione:\n/start: visualizza il messaggio iniziale.\n/gruppi: ottieni la lista di tutti i gruppi e canali ufficiali di Mozilla Italia.\n/supporto:
:) -> 😄

2020-04-05 21:06 UTC, Sav22999 commented on hub_mozita.py
> +"""
Spostarlo a riga `67` (sotto "adminlist")

2020-04-05 21:06 UTC, Sav22999 commented on social_list.json
> +  "Instagram": "https://github.com/Sav22999/mozitamyuserid_bot",
??? Instagram, non esiste al momento 😆 rimuoverlo

2020-04-05 21:06 UTC, Sav22999 commented on social_list.json
> +}
Aggiungere "Discourse": "https://discourse.mozilla.org/c/community-portal/mozilla-italia"

2020-04-06 09:35 UTC, ilyasmg commented
aggiornato

2020-04-06 15:43 UTC, Sav22999 approved these changes

2020-04-06 15:56 UTC, Sav22999 commented
Ok, ho fatto anche vari test e funziona tutto perfettamente.
Grazie mille @ilyasmg

2020-04-06 15:58 UTC, merged