v1.6.3 - marketing update!
MozillaItalia/mozitahub_bot pull request #65
Opened 2020-11-16 17:11 UTC by dag7dev

- added: marketing group + buttons + texts
- added: tuple as an import
- removed: threading as non-existent dependency
- updated: frasi.json now they include marketing texts + fixed typos

Closes #58 #60

2020-11-16 22:58 UTC, Sav22999 commented
Sto discutendo in chat privato con Damiano, poiché è più rapida come modalità

2020-11-18 14:16 UTC, Sav22999 requested changes

2020-11-18 14:16 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
?

2020-11-18 14:16 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
Perché hai rimosso "`{{**giorno_call**}}`" e compagnia bella?

2020-11-18 14:16 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
Modifica anche "HOME" in "Home"

2020-11-18 14:18 UTC, dag7dev commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
ora funzionano come avevamo già detto, e cioè lo impostiamo noi manualmente

2020-11-18 14:20 UTC, dag7dev commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
basta cambiare le variabili a inizio bot

2020-11-18 14:32 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
Ok, ma non deve mostrare il numero del mese come cifra, ma come valore letterario, come era prima. Inoltre, lascia "il" e togli "in data"

2020-11-18 14:33 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
E bisogna impostarli manualmente dal bot, non modificando il codice. Finché non viene implementata quella feature è inutile

2020-11-18 14:37 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
Deve essere necessario anche impostare l'orario, ovviamente. 
Se non presenta la data, allora deve mostrare un altro messaggio (fai una bozza e mando in revisione)

2020-11-18 14:39 UTC, dag7dev commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
c'è già l'ora e i minuti, vai nel codice. Sono delle stringhe, puoi impostare quello che vuoi.
Prima mostrava 01, non mostrava "il primo" o cose simili.

"Il" è stato tolto perchè non va bene se per caso il meeting si tiene in data 01 o 11.

2020-11-18 14:40 UTC, closed without merging

2020-11-18 14:45 UTC, Sav22999 commented on frasi.json
> +    "prossima_call": "Il prossimo meeting video comunitario si terrà in data <b>{}-{}-{}</b>, alle ore <b>{}:{}</b>.\nIl dato potrebbe subire variazioni (slittamenti o annullamenti).\nTi consigliamo
Metti un controllo se è "1" o "11", in quel caso mostra "l'" invece di "il"